### ISSUE TITLE
metadata.rb is missing

### ISSUE THREAD

**Issue by dahui** [poise/application#56] opened 2015-03-11 17:29 UTC
Hello,

Since there has not been a release of this cookbook in over a year, we have been using what is in the development git repository since keep_releases is broken in the officially released application cookbook on supermarket. 

It seems that in a recent commit, metadata.rb has been removed and is breaking Berkshelf's dependency resolution when pointed at the repo. Can it be replaced, and can we possibly get some new tagged releases out? :)

**Comment by coderanger** [comment] 2015-03-11 17:33
Duplicate of https://github.com/poise/application/issues/55

This is now a Halite-based cookbook.

**Closed** 2015-05-29 06:16 UTC
